LANG = {
	en : {
		createPlaylist : 'Create Playlist',
		newPlaylist : 'Playlist ({{date}})',
		emptyPlaylist : 'Search for music and drag it here',
		createAlbum : 'Create Album',
		emptyAlbum : 'Sorry, this album does not contain any songs',
		storeAlbum : 'Save Album',
		removeAlbum : 'Remove album',
		addSongs : 'Add songs',
		removePlaylist : 'Remove playlist',
		areYouSure : 'Are you sure?',
		albumTagPrompt : 'Search by genre',
		albumArtistPrompt : 'Search by artist',
		searchPrompt : 'Type a song, artist or genre',
		search : 'Search',
		loved : 'Songs you love',
		emptyLoved : 'You didn\'t loved any song',
		months : ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
		date : '{{month}} {{date}}'
	},
	es : {
		createPlaylist : 'Crear Playlist',
		newPlaylist : 'Playlist ({{date}})',
		emptyPlaylist : 'Busca música y arrástrala aquí',
		createAlbum : 'Crear Álbum',
		emptyAlbum : 'Lo siento, este álbum no contiene ninguna canción',
		storeAlbum : 'Guardar Álbum',
		removeAlbum : 'Eliminar álbum',
		addSongs : 'Añadir canciones',
		removePlaylist : 'Eliminar playlist',
		areYouSure : '¿Estás seguro?',
		albumTagPrompt : 'Buscar por género',
		albumArtistPrompt : 'Buscar por artista',
		searchPrompt : 'Teclea una canción, artista o género',
		search : 'Buscar',
		loved : 'Canciones que amas',
		emptyLoved : 'No has amado ninguna canción',
		months : ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
		date : '{{date}} {{month}}'
	}
};
