LANG = {
	en : {
		createPlaylist : 'Create Playlist',
		newPlaylist : 'Playlist ({{date}})',
		emptyPlaylist : 'Search for music and drag it here',
		createAlbum : 'Create Album',
		emptyAlbum : 'Sorry, this album does not contain any songs',
		moreFrom : 'More from',
		storeAlbum : 'Save Album',
		removeAlbum : 'Remove album',
		addSongs : 'Add songs',
		removePlaylist : 'Remove playlist',
		areYouSure : 'Are you sure?',
		searchPrompt : 'Search by artist or genre',
		searchSongPrompt : 'Type a song or artist',
		search : 'Search',
		artists : 'Artists',
		genres : 'Genres',
		loved : 'Songs you love',
		emptyLoved : 'You haven\'t loved any songs',
		emptyHomeArtist : 'There aren\'t any available albums from that artist',
		emptyHomeTag : 'There aren\'t any available albums with that genre',
		exploreOffline : 'Sorry, you are offline.',
		exploreOfflineB : 'You can still play your offline albums & playlists, though.',
		date : '{{month}} {{date}}',
		months : ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	},
	es : {
		createPlaylist : 'Crear Playlist',
		newPlaylist : 'Playlist ({{date}})',
		emptyPlaylist : 'Busca música y arrástrala aquí',
		createAlbum : 'Crear Álbum',
		emptyAlbum : 'Lo siento, este álbum no contiene ninguna canción',
		moreFrom : 'Más de',
		storeAlbum : 'Guardar Álbum',
		removeAlbum : 'Eliminar álbum',
		addSongs : 'Añadir canciones',
		removePlaylist : 'Eliminar playlist',
		areYouSure : '¿Estás seguro?',
		searchPrompt : 'Buscar por artista o género',
		searchSongPrompt : 'Teclea una canción, artista o género',
		search : 'Buscar',
		artists : 'Artistas',
		genres : 'Géneros',
		loved : 'Canciones que amas',
		emptyLoved : 'No has amado ninguna canción',
		emptyHomeArtist : 'No hay ningun álbum disponible de ese artista',
		emptyHomeTag : 'No hay ningun álbum disponible con ese género',
		exploreOffline : 'Lo siento, estás offline.',
		exploreOfflineB : 'Puedes seguir escuchando tus álbums y playlists offline de todos modos.',
		date : '{{date}} {{month}}',
		months : ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
	}
};
